// Package commit0.v1 defines the versioned gRPC plugin contract for commit0-analyzer.
//
// # Version and Compatibility Policy
//
// This contract is "v0-PROVISIONAL": the wire format is versioned at the message level
// (ProtocolVersion in MetadataResponse), but the schema is NOT yet frozen. Breaking
// changes may happen between Phase 1 and Phase 2. Once Phase 2 confirms the transport
// (subprocess/gRPC over stdio), the contract is frozen at v0.
//
// Compatibility rule: the host accepts a plugin when host.Major == plugin.Major AND
// host.Minor >= plugin.Minor. A plugin with a higher Minor than the host is rejected
// (host may be missing optional fields the plugin depends on). Minor bumps are additive
// (new optional fields only). Major bumps are breaking.
//
// # SARIF Mapping Intent
//
// Fields are chosen to lower cleanly into a SARIF 2.1 `result` + `codeFlows`:
//   - Finding.id        → result.ruleId
//   - Finding.severity  → result.level (Critical/High→error, Medium→warning, Low→note)
//   - Finding.advisory  → result.relatedLocations or rule.help
//   - ReachabilityPath  → result.codeFlows[0].threadFlows[0].locations
//   - Location          → physicalLocation { artifactLocation.uri, region.startLine/startColumn }
//   - Finding with no ReachabilityPath MUST omit codeFlows (an empty codeFlows array
//     invalidates a SARIF document and causes GitHub code scanning to reject the whole upload).
//
// # Analyze Stream Direction and Framing
//
// The Analyze RPC is a server-streaming call: the client (host) sends one AnalyzeRequest
// and the server (plugin) streams zero or more Finding messages back, closing the stream
// when analysis is complete. There is no client-side flow control; the plugin is expected
// to emit findings eagerly as they are discovered. The stream ends normally on a clean
// close; any error terminates the stream and is surfaced to the host as a gRPC status.
// Plugins MUST NOT buffer all findings and send them in a batch; hosts MUST tolerate
// findings arriving in any order.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: commit0/v1/plugin.proto

package commit0v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ecosystem identifies the package ecosystem / language a plugin operates on.
// This is an additive discriminator: Go/JS plugins that predate this field
// may omit it (zero value = ECOSYSTEM_UNKNOWN); the host infers the
// ecosystem from the plugin's MetadataResponse.supported_languages when the
// field is absent.
type Ecosystem int32

const (
	// ECOSYSTEM_UNKNOWN is the zero/default. Treated as unknown ecosystem.
	Ecosystem_ECOSYSTEM_UNKNOWN Ecosystem = 0
	// ECOSYSTEM_GO covers the Go module ecosystem (go.mod / go.sum).
	Ecosystem_ECOSYSTEM_GO Ecosystem = 1
	// ECOSYSTEM_NPM covers the npm / Node.js ecosystem (package.json / package-lock.json).
	Ecosystem_ECOSYSTEM_NPM Ecosystem = 2
	// ECOSYSTEM_CRATES_IO covers the Rust / Cargo ecosystem (Cargo.toml / Cargo.lock).
	Ecosystem_ECOSYSTEM_CRATES_IO Ecosystem = 3
	// ECOSYSTEM_PYPI covers the Python / PyPI ecosystem (pyproject.toml / requirements.txt).
	Ecosystem_ECOSYSTEM_PYPI Ecosystem = 4
	// ECOSYSTEM_MAVEN covers the Java / Maven and Gradle ecosystems (pom.xml / build.gradle).
	Ecosystem_ECOSYSTEM_MAVEN Ecosystem = 5
)

// Enum value maps for Ecosystem.
var (
	Ecosystem_name = map[int32]string{
		0: "ECOSYSTEM_UNKNOWN",
		1: "ECOSYSTEM_GO",
		2: "ECOSYSTEM_NPM",
		3: "ECOSYSTEM_CRATES_IO",
		4: "ECOSYSTEM_PYPI",
		5: "ECOSYSTEM_MAVEN",
	}
	Ecosystem_value = map[string]int32{
		"ECOSYSTEM_UNKNOWN":   0,
		"ECOSYSTEM_GO":        1,
		"ECOSYSTEM_NPM":       2,
		"ECOSYSTEM_CRATES_IO": 3,
		"ECOSYSTEM_PYPI":      4,
		"ECOSYSTEM_MAVEN":     5,
	}
)

func (x Ecosystem) Enum() *Ecosystem {
	p := new(Ecosystem)
	*p = x
	return p
}

func (x Ecosystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ecosystem) Descriptor() protoreflect.EnumDescriptor {
	return file_commit0_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Ecosystem) Type() protoreflect.EnumType {
	return &file_commit0_v1_plugin_proto_enumTypes[0]
}

func (x Ecosystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ecosystem.Descriptor instead.
func (Ecosystem) EnumDescriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Confidence describes how certain the analyzer is that a vulnerable symbol or
// package is actually reachable from an entry point.
//
// CRITICAL INVARIANT: unknown ≠ safe. A Finding with CONFIDENCE_UNKNOWN MUST be
// surfaced to the user; it MUST NOT be silently suppressed. Callers must treat
// unknown as "could not determine reachability" (e.g. reflection, dynamic
// dispatch, cgo, build-tag mismatch), NOT as "not reachable."
//
// The proto3 zero value is CONFIDENCE_UNKNOWN so that a freshly-deserialized or
// default-constructed Finding is conservative by default.
type Confidence int32

const (
	// CONFIDENCE_UNKNOWN is the zero/default value. Reachability could not be
	// determined (e.g. reflection, dynamic dispatch, incomplete build graph,
	// build-tag mismatch). This finding MUST be surfaced, never suppressed.
	Confidence_CONFIDENCE_UNKNOWN Confidence = 0
	// CONFIDENCE_NOT_REACHABLE means the analyzer found no call path from any
	// entry point to the vulnerable symbol/package. Only NOT_REACHABLE findings
	// may be suppressed by a policy gate.
	Confidence_CONFIDENCE_NOT_REACHABLE Confidence = 1
	// CONFIDENCE_PACKAGE_REACHABLE means the vulnerable package is imported and
	// reachable from an entry point, but the specific vulnerable symbol could not
	// be confirmed (symbol-level data unavailable or inconclusive).
	Confidence_CONFIDENCE_PACKAGE_REACHABLE Confidence = 2
	// CONFIDENCE_SYMBOL_REACHABLE means a concrete call-graph path from an entry
	// point to the specific vulnerable symbol was found. This is the highest
	// confidence tier; ReachabilityPath SHOULD be populated.
	Confidence_CONFIDENCE_SYMBOL_REACHABLE Confidence = 3
)

// Enum value maps for Confidence.
var (
	Confidence_name = map[int32]string{
		0: "CONFIDENCE_UNKNOWN",
		1: "CONFIDENCE_NOT_REACHABLE",
		2: "CONFIDENCE_PACKAGE_REACHABLE",
		3: "CONFIDENCE_SYMBOL_REACHABLE",
	}
	Confidence_value = map[string]int32{
		"CONFIDENCE_UNKNOWN":           0,
		"CONFIDENCE_NOT_REACHABLE":     1,
		"CONFIDENCE_PACKAGE_REACHABLE": 2,
		"CONFIDENCE_SYMBOL_REACHABLE":  3,
	}
)

func (x Confidence) Enum() *Confidence {
	p := new(Confidence)
	*p = x
	return p
}

func (x Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_commit0_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Confidence) Type() protoreflect.EnumType {
	return &file_commit0_v1_plugin_proto_enumTypes[1]
}

func (x Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confidence.Descriptor instead.
func (Confidence) EnumDescriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{1}
}

// Severity classifies the impact of a vulnerability.
type Severity int32

const (
	// SEVERITY_UNSPECIFIED is the zero/default. Treat as unknown severity.
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_commit0_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_commit0_v1_plugin_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{2}
}

// Location identifies a source position.
// Maps to SARIF physicalLocation { artifactLocation.uri, region.startLine/startColumn }.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file is a path relative to the module root (e.g. "pkg/foo/bar.go").
	File          string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Location) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// CallStep is one frame in a reachability call chain.
type CallStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// location is the call site (the line that calls the next step).
	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// symbol is the fully-qualified symbol at this call site (e.g. "pkg/foo.Bar").
	Symbol        string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStep) Reset() {
	*x = CallStep{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStep) ProtoMessage() {}

func (x *CallStep) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStep.ProtoReflect.Descriptor instead.
func (*CallStep) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CallStep) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CallStep) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// ReachabilityPath is a concrete call chain from an entry point to a vulnerable
// symbol. Maps to SARIF result.codeFlows[0].threadFlows[0].locations.
// Only populated when Confidence == CONFIDENCE_SYMBOL_REACHABLE.
type ReachabilityPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// steps is the ordered sequence of call frames, from entry point to
	// the vulnerable symbol (inclusive at both ends).
	Steps         []*CallStep `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReachabilityPath) Reset() {
	*x = ReachabilityPath{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityPath) ProtoMessage() {}

func (x *ReachabilityPath) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityPath.ProtoReflect.Descriptor instead.
func (*ReachabilityPath) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ReachabilityPath) GetSteps() []*CallStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// AdvisoryRef identifies the vulnerability this Finding relates to.
// Maps to SARIF result.ruleId + rule.help.
type AdvisoryRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the canonical advisory identifier (e.g. "GO-2024-0001", "CVE-2024-12345").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// url is a human-readable link to the advisory (optional).
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// aliases are alternative identifiers (e.g. CVEs when the primary id is a GHSA).
	Aliases       []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvisoryRef) Reset() {
	*x = AdvisoryRef{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisoryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisoryRef) ProtoMessage() {}

func (x *AdvisoryRef) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisoryRef.ProtoReflect.Descriptor instead.
func (*AdvisoryRef) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AdvisoryRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdvisoryRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdvisoryRef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Finding is the normalized output of a single vulnerability report from a plugin.
//
// SARIF lowering:
//   - id / advisory → result.ruleId + rule.help
//   - severity      → result.level
//   - path          → result.codeFlows (OMIT if nil/empty; empty codeFlows is invalid SARIF)
//   - properties    → result.properties (carries algorithm, snapshot_digest, goos, goarch, tags)
//   - pillar/lang   → reserved tags for multi-pillar expansion (SAST, Secrets, …)
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// advisory is the vulnerability reference this finding relates to.
	Advisory *AdvisoryRef `protobuf:"bytes,1,opt,name=advisory,proto3" json:"advisory,omitempty"`
	// module is the Go module path of the dependency containing the vulnerability
	// (e.g. "golang.org/x/net").
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// confidence is the analyzer's certainty about reachability.
	// The zero value is CONFIDENCE_UNKNOWN (conservative default).
	Confidence Confidence `protobuf:"varint,3,opt,name=confidence,proto3,enum=commit0.v1.Confidence" json:"confidence,omitempty"`
	// severity is the vulnerability's impact classification.
	Severity Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=commit0.v1.Severity" json:"severity,omitempty"`
	// path is the concrete call chain, if available.
	// MUST be nil/omitted when confidence < CONFIDENCE_SYMBOL_REACHABLE,
	// and MUST be populated when confidence == CONFIDENCE_SYMBOL_REACHABLE.
	Path *ReachabilityPath `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// properties carries analyzer metadata:
	//
	//	"goos"             → GOOS used for analysis
	//	"goarch"           → GOARCH used for analysis
	//	"tags"             → comma-separated build tags
	//	"snapshot_digest"  → hex digest of the advisory snapshot used
	//	"algorithm"        → call-graph algorithm (e.g. "vta", "rta", "cha")
	Properties map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pillar is a reserved tag for multi-pillar expansion (e.g. "sca", "sast", "secrets").
	// Populated by the host when aggregating findings from multiple plugin types.
	Pillar string `protobuf:"bytes,7,opt,name=pillar,proto3" json:"pillar,omitempty"`
	// language is a reserved tag for multi-language support (e.g. "go", "js", "python").
	Language string `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	// ecosystem identifies the package ecosystem this finding came from.
	// Optional; Go/JS plugins that predate this field may leave it at the
	// zero value (ECOSYSTEM_UNKNOWN). New plugins SHOULD set this so findings
	// can be grouped and filtered per ecosystem without parsing the language string.
	Ecosystem Ecosystem `protobuf:"varint,9,opt,name=ecosystem,proto3,enum=commit0.v1.Ecosystem" json:"ecosystem,omitempty"`
	// incomplete signals that the analysis producing this finding was partial:
	// the plugin could not fully resolve the dependency graph or call graph, so
	// additional vulnerable paths may exist that were not checked. When true,
	// the host MUST set the scan-level incomplete flag. The zero value (false)
	// means analysis was complete for this finding's dependency.
	Incomplete    bool `protobuf:"varint,10,opt,name=incomplete,proto3" json:"incomplete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetAdvisory() *AdvisoryRef {
	if x != nil {
		return x.Advisory
	}
	return nil
}

func (x *Finding) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Finding) GetConfidence() Confidence {
	if x != nil {
		return x.Confidence
	}
	return Confidence_CONFIDENCE_UNKNOWN
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetPath() *ReachabilityPath {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Finding) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Finding) GetPillar() string {
	if x != nil {
		return x.Pillar
	}
	return ""
}

func (x *Finding) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Finding) GetEcosystem() Ecosystem {
	if x != nil {
		return x.Ecosystem
	}
	return Ecosystem_ECOSYSTEM_UNKNOWN
}

func (x *Finding) GetIncomplete() bool {
	if x != nil {
		return x.Incomplete
	}
	return false
}

// Symbol identifies a specific function or method within a package.
type Symbol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// package is the fully-qualified Go package path (e.g. "crypto/tls").
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// name is the symbol name within the package (e.g. "Conn.Read").
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Symbol) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Advisory carries a resolved vulnerability from the advisory service to the analyzer.
// The host (Phase 2) resolves advisories and embeds them in AnalyzeRequest; the
// standalone runner (Phase 4) constructs an identical AnalyzeRequest from the same
// source, so both paths share one request type with no divergent plumbing.
type Advisory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the canonical advisory identifier (e.g. "GO-2024-0001").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// module is the affected Go module path.
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// version_range is the affected version range in semver notation (e.g. "<1.2.3").
	VersionRange string `protobuf:"bytes,3,opt,name=version_range,json=versionRange,proto3" json:"version_range,omitempty"`
	// symbols are the specific vulnerable symbols, if known (Go vuln DB provides these).
	Symbols []*Symbol `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"`
	// symbol_level indicates whether symbol-level data is available for this advisory.
	// When false, the analyzer MUST degrade to CONFIDENCE_PACKAGE_REACHABLE at best.
	SymbolLevel bool `protobuf:"varint,5,opt,name=symbol_level,json=symbolLevel,proto3" json:"symbol_level,omitempty"`
	// sources lists the advisory data sources (e.g. ["go-vuln-db"]).
	Sources []string `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	// ecosystem identifies the package ecosystem this advisory applies to.
	// Optional; Go/JS advisories may omit this field (pre-dates the multi-language
	// extension). New plugins SHOULD set this so the host can route version
	// comparison to the correct per-ecosystem comparator.
	Ecosystem     Ecosystem `protobuf:"varint,7,opt,name=ecosystem,proto3,enum=commit0.v1.Ecosystem" json:"ecosystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advisory) Reset() {
	*x = Advisory{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advisory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advisory) ProtoMessage() {}

func (x *Advisory) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advisory.ProtoReflect.Descriptor instead.
func (*Advisory) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Advisory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Advisory) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Advisory) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

func (x *Advisory) GetSymbols() []*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Advisory) GetSymbolLevel() bool {
	if x != nil {
		return x.SymbolLevel
	}
	return false
}

func (x *Advisory) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Advisory) GetEcosystem() Ecosystem {
	if x != nil {
		return x.Ecosystem
	}
	return Ecosystem_ECOSYSTEM_UNKNOWN
}

// BuildConfig specifies the build environment for analysis.
// When the analysis target cannot be built for the specified config, the analyzer
// MUST degrade to CONFIDENCE_UNKNOWN (never NOT_REACHABLE) for affected findings.
type BuildConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// goos is the target GOOS (e.g. "linux", "darwin", "windows").
	Goos string `protobuf:"bytes,1,opt,name=goos,proto3" json:"goos,omitempty"`
	// goarch is the target GOARCH (e.g. "amd64", "arm64").
	Goarch string `protobuf:"bytes,2,opt,name=goarch,proto3" json:"goarch,omitempty"`
	// tags are additional build tags to apply during analysis.
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildConfig) Reset() {
	*x = BuildConfig{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildConfig) ProtoMessage() {}

func (x *BuildConfig) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildConfig.ProtoReflect.Descriptor instead.
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *BuildConfig) GetGoos() string {
	if x != nil {
		return x.Goos
	}
	return ""
}

func (x *BuildConfig) GetGoarch() string {
	if x != nil {
		return x.Goarch
	}
	return ""
}

func (x *BuildConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// EcosystemBuildConfig carries per-ecosystem build context for non-Go plugins.
// It gives Rust, Python, and future language plugins a dedicated place for their
// build environment rather than overloading the Go-specific goos/goarch fields.
// This message is optional and non-breaking: Go/JS plugins ignore it.
type EcosystemBuildConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ecosystem identifies which ecosystem this build config applies to.
	Ecosystem Ecosystem `protobuf:"varint,1,opt,name=ecosystem,proto3,enum=commit0.v1.Ecosystem" json:"ecosystem,omitempty"`
	// target_triple is the ecosystem-specific build target descriptor.
	// Rust: Cargo target triple (e.g. "x86_64-unknown-linux-gnu").
	// Python: platform tag (e.g. "linux_x86_64").
	// Absent for Go (use BuildConfig.goos/goarch instead).
	TargetTriple string `protobuf:"bytes,2,opt,name=target_triple,json=targetTriple,proto3" json:"target_triple,omitempty"`
	// features are ecosystem-specific feature flags to enable during analysis.
	// Rust: Cargo feature names (e.g. ["serde", "tokio/full"]).
	// Python: extras (e.g. ["dev", "test"]).
	Features []string `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	// python_version is the Python interpreter version string (e.g. "3.11.4").
	// Only meaningful for ECOSYSTEM_PYPI; ignored by other ecosystems.
	PythonVersion string `protobuf:"bytes,4,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	// extra_env carries additional key=value environment variables the plugin
	// needs to replicate the project's build environment. Only values that are
	// SAFE TO EXPOSE should be set here (no secrets, no credentials).
	ExtraEnv      map[string]string `protobuf:"bytes,5,rep,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcosystemBuildConfig) Reset() {
	*x = EcosystemBuildConfig{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcosystemBuildConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcosystemBuildConfig) ProtoMessage() {}

func (x *EcosystemBuildConfig) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcosystemBuildConfig.ProtoReflect.Descriptor instead.
func (*EcosystemBuildConfig) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *EcosystemBuildConfig) GetEcosystem() Ecosystem {
	if x != nil {
		return x.Ecosystem
	}
	return Ecosystem_ECOSYSTEM_UNKNOWN
}

func (x *EcosystemBuildConfig) GetTargetTriple() string {
	if x != nil {
		return x.TargetTriple
	}
	return ""
}

func (x *EcosystemBuildConfig) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EcosystemBuildConfig) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *EcosystemBuildConfig) GetExtraEnv() map[string]string {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

// ResolvedDependency is one entry in the host's already-parsed dependency
// closure for a lockfile-static ecosystem. The host resolves the closure from
// the project's lockfile and passes it to the reachability plugin so the plugin
// consumes the closure directly and never re-parses the lockfile in its own
// language (DRY + smaller ACE surface: seven parsers already exist host-side).
//
// This message is optional and additive: plugins that predate it ignore the
// resolved_deps field entirely (they resolve their own closure). New
// lockfile-backed plugins advertise protocol minor >= 2 and consume it.
type ResolvedDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the ecosystem-specific package name (e.g. "org.springframework:spring-core").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the resolved version string from the lockfile.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// dep_type is the dependency classification from the lockfile:
	// "runtime", "dev", "test", "optional", or "" (unknown, treated as runtime).
	DepType string `protobuf:"bytes,3,opt,name=dep_type,json=depType,proto3" json:"dep_type,omitempty"`
	// ecosystem identifies which ecosystem this dependency belongs to.
	Ecosystem     Ecosystem `protobuf:"varint,4,opt,name=ecosystem,proto3,enum=commit0.v1.Ecosystem" json:"ecosystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedDependency) Reset() {
	*x = ResolvedDependency{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedDependency) ProtoMessage() {}

func (x *ResolvedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedDependency.ProtoReflect.Descriptor instead.
func (*ResolvedDependency) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvedDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedDependency) GetDepType() string {
	if x != nil {
		return x.DepType
	}
	return ""
}

func (x *ResolvedDependency) GetEcosystem() Ecosystem {
	if x != nil {
		return x.Ecosystem
	}
	return Ecosystem_ECOSYSTEM_UNKNOWN
}

// AnalyzeRequest is the single input type for the Analyze RPC.
// Used by both the plugin host (Phase 2) and the standalone runner (Phase 4);
// there is exactly one request type — no divergent advisory plumbing.
type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// module_root is the absolute path to the Go module root directory.
	ModuleRoot string `protobuf:"bytes,1,opt,name=module_root,json=moduleRoot,proto3" json:"module_root,omitempty"`
	// entrypoints are the packages to use as analysis roots (e.g. ["./cmd/myapp"]).
	// When empty, the analyzer auto-detects entry points based on the module type
	// (main packages → main+init+tests; library → exported symbols + init).
	Entrypoints []string `protobuf:"bytes,2,rep,name=entrypoints,proto3" json:"entrypoints,omitempty"`
	// build_config specifies the build environment for analysis.
	BuildConfig *BuildConfig `protobuf:"bytes,3,opt,name=build_config,json=buildConfig,proto3" json:"build_config,omitempty"`
	// advisories are the resolved vulnerabilities to check reachability for.
	Advisories []*Advisory `protobuf:"bytes,4,rep,name=advisories,proto3" json:"advisories,omitempty"`
	// ecosystem_build_config carries per-ecosystem build context for non-Go plugins.
	// Optional and additive: Go/JS plugins ignore this field. New language plugins
	// (Rust, Python) use this instead of overloading the Go-specific build_config.
	EcosystemBuildConfig *EcosystemBuildConfig `protobuf:"bytes,5,opt,name=ecosystem_build_config,json=ecosystemBuildConfig,proto3" json:"ecosystem_build_config,omitempty"`
	// resolved_deps is the host's already-parsed dependency closure for
	// lockfile-static ecosystems. A lockfile-backed reachability plugin consumes
	// this closure instead of re-parsing the lockfile. Optional and additive:
	// older plugins ignore it and resolve their own closure.
	ResolvedDeps []*ResolvedDependency `protobuf:"bytes,6,rep,name=resolved_deps,json=resolvedDeps,proto3" json:"resolved_deps,omitempty"`
	// closure_incomplete is true when any host-side adapter returned a partial
	// closure (complete=false). When true, a plugin MUST NOT emit NOT_REACHABLE:
	// a package that appears unreferenced could still be pulled in by an
	// unresolved transitive dependency. This is the wire-level guard against a
	// false NOT_REACHABLE proven over an incomplete closure ("unknown ≠ safe").
	ClosureIncomplete bool `protobuf:"varint,7,opt,name=closure_incomplete,json=closureIncomplete,proto3" json:"closure_incomplete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeRequest) GetModuleRoot() string {
	if x != nil {
		return x.ModuleRoot
	}
	return ""
}

func (x *AnalyzeRequest) GetEntrypoints() []string {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

func (x *AnalyzeRequest) GetBuildConfig() *BuildConfig {
	if x != nil {
		return x.BuildConfig
	}
	return nil
}

func (x *AnalyzeRequest) GetAdvisories() []*Advisory {
	if x != nil {
		return x.Advisories
	}
	return nil
}

func (x *AnalyzeRequest) GetEcosystemBuildConfig() *EcosystemBuildConfig {
	if x != nil {
		return x.EcosystemBuildConfig
	}
	return nil
}

func (x *AnalyzeRequest) GetResolvedDeps() []*ResolvedDependency {
	if x != nil {
		return x.ResolvedDeps
	}
	return nil
}

func (x *AnalyzeRequest) GetClosureIncomplete() bool {
	if x != nil {
		return x.ClosureIncomplete
	}
	return false
}

// MetadataRequest is sent by the host to identify itself during the handshake.
type MetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_version is the host's protocol version string (e.g. "0.1").
	HostVersion   string `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

// MetadataResponse is returned by a plugin to describe itself.
type MetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin's human-readable name (e.g. "go-reachability").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin's own semantic version (e.g. "0.1.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// protocol_version is the protocol version this plugin implements (e.g. "0.1").
	// The host uses this to decide compatibility before calling Analyze.
	ProtocolVersion string `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// description is a short human-readable description of what the plugin analyzes.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// supported_languages lists the programming language pillars this plugin handles.
	SupportedLanguages []string `protobuf:"bytes,5,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_commit0_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commit0_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_commit0_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

var File_commit0_v1_plugin_proto protoreflect.FileDescriptor

const file_commit0_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x17commit0/v1/plugin.proto\x12\n" +
	"commit0.v1\"J\n" +
	"\bLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"T\n" +
	"\bCallStep\x120\n" +
	"\blocation\x18\x01 \x01(\v2\x14.commit0.v1.LocationR\blocation\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\">\n" +
	"\x10ReachabilityPath\x12*\n" +
	"\x05steps\x18\x01 \x03(\v2\x14.commit0.v1.CallStepR\x05steps\"I\n" +
	"\vAdvisoryRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\"\xff\x03\n" +
	"\aFinding\x123\n" +
	"\badvisory\x18\x01 \x01(\v2\x17.commit0.v1.AdvisoryRefR\badvisory\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x126\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x0e2\x16.commit0.v1.ConfidenceR\n" +
	"confidence\x120\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x14.commit0.v1.SeverityR\bseverity\x120\n" +
	"\x04path\x18\x05 \x01(\v2\x1c.commit0.v1.ReachabilityPathR\x04path\x12C\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2#.commit0.v1.Finding.PropertiesEntryR\n" +
	"properties\x12\x16\n" +
	"\x06pillar\x18\a \x01(\tR\x06pillar\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x123\n" +
	"\tecosystem\x18\t \x01(\x0e2\x15.commit0.v1.EcosystemR\tecosystem\x12\x1e\n" +
	"\n" +
	"incomplete\x18\n" +
	" \x01(\bR\n" +
	"incomplete\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x06Symbol\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf7\x01\n" +
	"\bAdvisory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12#\n" +
	"\rversion_range\x18\x03 \x01(\tR\fversionRange\x12,\n" +
	"\asymbols\x18\x04 \x03(\v2\x12.commit0.v1.SymbolR\asymbols\x12!\n" +
	"\fsymbol_level\x18\x05 \x01(\bR\vsymbolLevel\x12\x18\n" +
	"\asources\x18\x06 \x03(\tR\asources\x123\n" +
	"\tecosystem\x18\a \x01(\x0e2\x15.commit0.v1.EcosystemR\tecosystem\"M\n" +
	"\vBuildConfig\x12\x12\n" +
	"\x04goos\x18\x01 \x01(\tR\x04goos\x12\x16\n" +
	"\x06goarch\x18\x02 \x01(\tR\x06goarch\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\xbd\x02\n" +
	"\x14EcosystemBuildConfig\x123\n" +
	"\tecosystem\x18\x01 \x01(\x0e2\x15.commit0.v1.EcosystemR\tecosystem\x12#\n" +
	"\rtarget_triple\x18\x02 \x01(\tR\ftargetTriple\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12%\n" +
	"\x0epython_version\x18\x04 \x01(\tR\rpythonVersion\x12K\n" +
	"\textra_env\x18\x05 \x03(\v2..commit0.v1.EcosystemBuildConfig.ExtraEnvEntryR\bextraEnv\x1a;\n" +
	"\rExtraEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x12ResolvedDependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bdep_type\x18\x03 \x01(\tR\adepType\x123\n" +
	"\tecosystem\x18\x04 \x01(\x0e2\x15.commit0.v1.EcosystemR\tecosystem\"\x91\x03\n" +
	"\x0eAnalyzeRequest\x12\x1f\n" +
	"\vmodule_root\x18\x01 \x01(\tR\n" +
	"moduleRoot\x12 \n" +
	"\ventrypoints\x18\x02 \x03(\tR\ventrypoints\x12:\n" +
	"\fbuild_config\x18\x03 \x01(\v2\x17.commit0.v1.BuildConfigR\vbuildConfig\x124\n" +
	"\n" +
	"advisories\x18\x04 \x03(\v2\x14.commit0.v1.AdvisoryR\n" +
	"advisories\x12V\n" +
	"\x16ecosystem_build_config\x18\x05 \x01(\v2 .commit0.v1.EcosystemBuildConfigR\x14ecosystemBuildConfig\x12C\n" +
	"\rresolved_deps\x18\x06 \x03(\v2\x1e.commit0.v1.ResolvedDependencyR\fresolvedDeps\x12-\n" +
	"\x12closure_incomplete\x18\a \x01(\bR\x11closureIncomplete\"4\n" +
	"\x0fMetadataRequest\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\"\xbe\x01\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\x13supported_languages\x18\x05 \x03(\tR\x12supportedLanguages*\x89\x01\n" +
	"\tEcosystem\x12\x15\n" +
	"\x11ECOSYSTEM_UNKNOWN\x10\x00\x12\x10\n" +
	"\fECOSYSTEM_GO\x10\x01\x12\x11\n" +
	"\rECOSYSTEM_NPM\x10\x02\x12\x17\n" +
	"\x13ECOSYSTEM_CRATES_IO\x10\x03\x12\x12\n" +
	"\x0eECOSYSTEM_PYPI\x10\x04\x12\x13\n" +
	"\x0fECOSYSTEM_MAVEN\x10\x05*\x85\x01\n" +
	"\n" +
	"Confidence\x12\x16\n" +
	"\x12CONFIDENCE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18CONFIDENCE_NOT_REACHABLE\x10\x01\x12 \n" +
	"\x1cCONFIDENCE_PACKAGE_REACHABLE\x10\x02\x12\x1f\n" +
	"\x1bCONFIDENCE_SYMBOL_REACHABLE\x10\x03*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x042\x8f\x01\n" +
	"\bAnalyzer\x12E\n" +
	"\bMetadata\x12\x1b.commit0.v1.MetadataRequest\x1a\x1c.commit0.v1.MetadataResponse\x12<\n" +
	"\aAnalyze\x12\x1a.commit0.v1.AnalyzeRequest\x1a\x13.commit0.v1.Finding0\x01B@Z>github.com/commit0-dev/commit0-analyzer/pkg/contract/commit0v1b\x06proto3"

var (
	file_commit0_v1_plugin_proto_rawDescOnce sync.Once
	file_commit0_v1_plugin_proto_rawDescData []byte
)

func file_commit0_v1_plugin_proto_rawDescGZIP() []byte {
	file_commit0_v1_plugin_proto_rawDescOnce.Do(func() {
		file_commit0_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commit0_v1_plugin_proto_rawDesc), len(file_commit0_v1_plugin_proto_rawDesc)))
	})
	return file_commit0_v1_plugin_proto_rawDescData
}

var file_commit0_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_commit0_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_commit0_v1_plugin_proto_goTypes = []any{
	(Ecosystem)(0),               // 0: commit0.v1.Ecosystem
	(Confidence)(0),              // 1: commit0.v1.Confidence
	(Severity)(0),                // 2: commit0.v1.Severity
	(*Location)(nil),             // 3: commit0.v1.Location
	(*CallStep)(nil),             // 4: commit0.v1.CallStep
	(*ReachabilityPath)(nil),     // 5: commit0.v1.ReachabilityPath
	(*AdvisoryRef)(nil),          // 6: commit0.v1.AdvisoryRef
	(*Finding)(nil),              // 7: commit0.v1.Finding
	(*Symbol)(nil),               // 8: commit0.v1.Symbol
	(*Advisory)(nil),             // 9: commit0.v1.Advisory
	(*BuildConfig)(nil),          // 10: commit0.v1.BuildConfig
	(*EcosystemBuildConfig)(nil), // 11: commit0.v1.EcosystemBuildConfig
	(*ResolvedDependency)(nil),   // 12: commit0.v1.ResolvedDependency
	(*AnalyzeRequest)(nil),       // 13: commit0.v1.AnalyzeRequest
	(*MetadataRequest)(nil),      // 14: commit0.v1.MetadataRequest
	(*MetadataResponse)(nil),     // 15: commit0.v1.MetadataResponse
	nil,                          // 16: commit0.v1.Finding.PropertiesEntry
	nil,                          // 17: commit0.v1.EcosystemBuildConfig.ExtraEnvEntry
}
var file_commit0_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: commit0.v1.CallStep.location:type_name -> commit0.v1.Location
	4,  // 1: commit0.v1.ReachabilityPath.steps:type_name -> commit0.v1.CallStep
	6,  // 2: commit0.v1.Finding.advisory:type_name -> commit0.v1.AdvisoryRef
	1,  // 3: commit0.v1.Finding.confidence:type_name -> commit0.v1.Confidence
	2,  // 4: commit0.v1.Finding.severity:type_name -> commit0.v1.Severity
	5,  // 5: commit0.v1.Finding.path:type_name -> commit0.v1.ReachabilityPath
	16, // 6: commit0.v1.Finding.properties:type_name -> commit0.v1.Finding.PropertiesEntry
	0,  // 7: commit0.v1.Finding.ecosystem:type_name -> commit0.v1.Ecosystem
	8,  // 8: commit0.v1.Advisory.symbols:type_name -> commit0.v1.Symbol
	0,  // 9: commit0.v1.Advisory.ecosystem:type_name -> commit0.v1.Ecosystem
	0,  // 10: commit0.v1.EcosystemBuildConfig.ecosystem:type_name -> commit0.v1.Ecosystem
	17, // 11: commit0.v1.EcosystemBuildConfig.extra_env:type_name -> commit0.v1.EcosystemBuildConfig.ExtraEnvEntry
	0,  // 12: commit0.v1.ResolvedDependency.ecosystem:type_name -> commit0.v1.Ecosystem
	10, // 13: commit0.v1.AnalyzeRequest.build_config:type_name -> commit0.v1.BuildConfig
	9,  // 14: commit0.v1.AnalyzeRequest.advisories:type_name -> commit0.v1.Advisory
	11, // 15: commit0.v1.AnalyzeRequest.ecosystem_build_config:type_name -> commit0.v1.EcosystemBuildConfig
	12, // 16: commit0.v1.AnalyzeRequest.resolved_deps:type_name -> commit0.v1.ResolvedDependency
	14, // 17: commit0.v1.Analyzer.Metadata:input_type -> commit0.v1.MetadataRequest
	13, // 18: commit0.v1.Analyzer.Analyze:input_type -> commit0.v1.AnalyzeRequest
	15, // 19: commit0.v1.Analyzer.Metadata:output_type -> commit0.v1.MetadataResponse
	7,  // 20: commit0.v1.Analyzer.Analyze:output_type -> commit0.v1.Finding
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_commit0_v1_plugin_proto_init() }
func file_commit0_v1_plugin_proto_init() {
	if File_commit0_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commit0_v1_plugin_proto_rawDesc), len(file_commit0_v1_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commit0_v1_plugin_proto_goTypes,
		DependencyIndexes: file_commit0_v1_plugin_proto_depIdxs,
		EnumInfos:         file_commit0_v1_plugin_proto_enumTypes,
		MessageInfos:      file_commit0_v1_plugin_proto_msgTypes,
	}.Build()
	File_commit0_v1_plugin_proto = out.File
	file_commit0_v1_plugin_proto_goTypes = nil
	file_commit0_v1_plugin_proto_depIdxs = nil
}
