package cli

// ecosystem_nuget.go — lockfile-static adapter for NuGet (.NET/C#).
//
// OSV ecosystem: "NuGet" (https://osv.dev/list?ecosystem=NuGet)
// Maximum confidence: PACKAGE_REACHABLE (NuGet OSV advisories carry no method-level data).
//
// Security invariants (ACE-safety):
//   - NEVER run dotnet restore, MSBuild, or any build-tool wrapper. They can execute
//     PowerShell/MSBuild scripts from packages (install.ps1, init.ps1), which is
//     arbitrary code execution on untrusted repos.
//   - Parse ONLY the static lockfile (packages.lock.json or obj/project.assets.json).
//   - For packages.config, parse the XML statically (it lists all resolved packages).
//   - For .csproj-only projects, parse declared PackageReference elements and return
//     complete=false (transitives unknown without running dotnet restore).
//
// Lockfile resolution priority:
//  1. packages.lock.json — opt-in portable lockfile; full transitive closure. complete=true.
//  2. obj/project.assets.json — auto-generated by dotnet restore/build; full closure. complete=true.
//  3. packages.config — legacy XML; all packages listed explicitly. complete=true.
//  4. *.csproj only — declared (direct) deps; transitives unknown. complete=false.
//  5. Nothing found — complete=false.
//
// Dep-type classification:
//   - packages.lock.json / project.assets.json do NOT carry PrivateAssets metadata.
//     All packages from these lockfiles default to DepType="runtime" (conservative).
//     Unknown ≠ safe: inferring "test" from a name prefix risks suppressing a real
//     runtime advisory if the name happens to match a test-SDK prefix. Lockfile-only
//     scans cannot distinguish runtime from dev/test; segmentation requires the .csproj.
//   - packages.config: uses developmentDependency="true" attribute (authoritative).
//   - .csproj: uses <PrivateAssets>All</PrivateAssets> attribute (authoritative).
//     This is the ONLY authoritative dev/test marker. Without it, all refs default
//     to "runtime" — even packages whose names look like test SDKs.

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/commit0-dev/commit0-analyzer/internal/advisory"
)

func init() {
	RegisterEcosystemAdapter(EcosystemAdapter{
		Ecosystem: advisory.EcosystemNuGet,
		Language:  "dotnet",
		// DetectFiles: packages.lock.json and packages.config are exact filenames.
		// "*.csproj" is a glob pattern supported by detectEcosystems via the
		// hasFileSuffix helper; it detects SDK-style projects that have not opted
		// into lockfile-based restore.
		DetectFiles:   []string{"packages.lock.json", "packages.config", "*.csproj"},
		MaxConfidence: ceilingPackage,
		ParseLockfile: parseNugetLockfile,
		// NormalizeName is nil: NuGet package names in OSV records use their published
		// casing (e.g., "Newtonsoft.Json"). The NuGet registry is case-insensitive but
		// OSV bundle records are stored with canonical casing — do NOT lowercase.
		NormalizeName: nil,
	})
}

// parseNugetLockfile is the EcosystemAdapter.ParseLockfile implementation for the
// NuGet (.NET/C#) ecosystem.
//
// It tries four lockfile sources in descending fidelity order:
//  1. packages.lock.json — full transitive closure, complete=true.
//  2. obj/project.assets.json — full transitive closure from build output, complete=true.
//  3. packages.config — legacy explicit list, complete=true.
//  4. *.csproj — declared deps only, transitives unknown, complete=false.
//
// NEVER returns a partial closure with complete=false (EcosystemAdapter contract):
// a partial dep list would cause false NOT_REACHABLE for the missing transitive
// portion, silently dropping real vulnerabilities.
func parseNugetLockfile(root string) ([]ResolvedDep, bool, error) {
	// 1. packages.lock.json — preferred, opt-in, portable.
	deps, complete, err := parsePackagesLockJSON(filepath.Join(root, "packages.lock.json"))
	if err != nil {
		return nil, false, err
	}
	if complete {
		return deps, true, nil
	}

	// 2. obj/project.assets.json — auto-generated by dotnet restore / dotnet build.
	// Accepted only if it was already generated (e.g. in CI after a prior build).
	// Never regenerate it (that would require running dotnet restore = ACE).
	deps, complete, err = parseProjectAssetsJSON(filepath.Join(root, "obj", "project.assets.json"))
	if err != nil {
		return nil, false, err
	}
	if complete {
		return deps, true, nil
	}

	// 3. packages.config — legacy XML format; all packages listed with pinned versions.
	deps, complete, err = parsePackagesConfig(filepath.Join(root, "packages.config"))
	if err != nil {
		return nil, false, err
	}
	if complete {
		return deps, true, nil
	}

	// 4. *.csproj fallback — declared (direct) deps only; transitives unknown without
	// running dotnet restore (ACE risk on untrusted repos). Returns complete=false so
	// the caller marks the scan incomplete (unknown ≠ safe).
	return parseCsprojDir(root)
}

// ── packages.lock.json ───────────────────────────────────────────────────────

// packagesLockFile is the Go model for packages.lock.json (NuGet lockfile v1).
//
// Structure:
//
//	{
//	  "version": 1,
//	  "dependencies": {
//	    ".NETCoreApp,Version=v6.0": {
//	      "PackageName": {
//	        "type": "Direct" | "Transitive" | "Project",
//	        "resolved": "1.2.3",
//	        ...
//	      }
//	    }
//	  }
//	}
//
// The same package may appear under multiple target frameworks (TFMs) with the
// same version; entries are deduplicated by (name, version) before returning.
type packagesLockFile struct {
	Version      int                               `json:"version"`
	Dependencies map[string]map[string]pkgLockDep `json:"dependencies"`
}

type pkgLockDep struct {
	Type     string `json:"type"`
	Resolved string `json:"resolved"`
}

// parsePackagesLockJSON parses a packages.lock.json file at path.
//
// Returns (nil, false, nil) when the file does not exist.
// Returns (deps, true, nil) when the file is present and parseable.
// Returns (nil, false, err) on I/O or JSON decode errors.
func parsePackagesLockJSON(path string) ([]ResolvedDep, bool, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, false, fmt.Errorf("open packages.lock.json: %w", err)
	}
	defer func() { _ = f.Close() }()

	var lock packagesLockFile
	if err := json.NewDecoder(f).Decode(&lock); err != nil {
		return nil, false, fmt.Errorf("decode packages.lock.json: %w", err)
	}

	// Deduplicate across TFMs: a package can appear under multiple target
	// frameworks with identical coordinates — include it once.
	seen := make(map[string]bool) // lower(name)+"@"+version → already included
	var deps []ResolvedDep

	for _, tfmPkgs := range lock.Dependencies {
		for name, entry := range tfmPkgs {
			// Skip project references; they are not NuGet packages.
			if strings.EqualFold(entry.Type, "Project") {
				continue
			}
			version := entry.Resolved
			if version == "" {
				// No resolved version — cannot query OSV for an unpinned dep.
				// Skip silently: the overall closure is still complete (all other
				// deps have pinned versions); this edge case occurs when the
				// lockfile was written by a partial restore that left gaps.
				continue
			}
			key := strings.ToLower(name) + "@" + version
			if seen[key] {
				continue
			}
			seen[key] = true
			deps = append(deps, ResolvedDep{
				Name:    name,
				Version: version,
				// packages.lock.json carries no PrivateAssets metadata; default to
				// "runtime" (conservative). Unknown ≠ safe: never infer "test" from
				// a name prefix and risk suppressing a real runtime advisory.
				// Authoritative dep-type segmentation requires the .csproj.
				DepType: "runtime",
			})
		}
	}

	return deps, true, nil
}

// ── obj/project.assets.json ──────────────────────────────────────────────────

// projectAssetsFile is the Go model for obj/project.assets.json (NuGet assets v3).
//
// Structure (relevant excerpt):
//
//	{
//	  "version": 3,
//	  "targets": {
//	    ".NETCoreApp,Version=v6.0": {
//	      "PackageName/1.2.3": { "type": "package", ... }
//	    }
//	  }
//	}
//
// The "targets" key is a map of TFM (possibly with RID, e.g. "linux-x64") to a
// map of "PackageName/Version" strings. The same package can appear under
// multiple TFMs/RIDs; entries are deduplicated.
type projectAssetsFile struct {
	Version int                               `json:"version"`
	Targets map[string]map[string]assetTarget `json:"targets"`
}

type assetTarget struct {
	Type string `json:"type"`
}

// parseProjectAssetsJSON parses obj/project.assets.json at path.
//
// Returns (nil, false, nil) when the file does not exist.
// Returns (deps, true, nil) when the file is present and parseable.
// Returns (nil, false, err) on I/O or JSON decode errors.
func parseProjectAssetsJSON(path string) ([]ResolvedDep, bool, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, false, fmt.Errorf("open project.assets.json: %w", err)
	}
	defer func() { _ = f.Close() }()

	var assets projectAssetsFile
	if err := json.NewDecoder(f).Decode(&assets); err != nil {
		return nil, false, fmt.Errorf("decode project.assets.json: %w", err)
	}

	seen := make(map[string]bool) // lower(name)+"@"+version → already included
	var deps []ResolvedDep

	for _, tfmPkgs := range assets.Targets {
		for key, entry := range tfmPkgs {
			// Skip non-package entries (project references have type "project").
			if !strings.EqualFold(entry.Type, "package") {
				continue
			}
			// Key format: "PackageName/1.2.3"
			slash := strings.LastIndex(key, "/")
			if slash < 0 || slash == 0 || slash == len(key)-1 {
				continue // malformed key; skip
			}
			name := key[:slash]
			version := key[slash+1:]
			if name == "" || version == "" {
				continue
			}
			dedupeKey := strings.ToLower(name) + "@" + version
			if seen[dedupeKey] {
				continue
			}
			seen[dedupeKey] = true
			deps = append(deps, ResolvedDep{
				Name:    name,
				Version: version,
				// project.assets.json carries no PrivateAssets metadata; default to
				// "runtime" (conservative). Unknown ≠ safe: never infer "test" from
				// a name prefix and risk suppressing a real runtime advisory.
				// Authoritative dep-type segmentation requires the .csproj.
				DepType: "runtime",
			})
		}
	}

	return deps, true, nil
}

// ── packages.config ──────────────────────────────────────────────────────────

// packagesConfigFile is the Go model for packages.config (legacy NuGet XML format).
//
// Structure:
//
//	<?xml version="1.0" encoding="utf-8"?>
//	<packages>
//	  <package id="PackageName" version="1.2.3" targetFramework="net472"
//	           developmentDependency="true" />
//	</packages>
//
// The developmentDependency attribute signals that the package is only used
// during development/testing and should not be included in a consuming project.
type packagesConfigFile struct {
	XMLName  xml.Name           `xml:"packages"`
	Packages []packagesConfigPkg `xml:"package"`
}

type packagesConfigPkg struct {
	ID                    string `xml:"id,attr"`
	Version               string `xml:"version,attr"`
	DevelopmentDependency string `xml:"developmentDependency,attr"`
}

// parsePackagesConfig parses a packages.config file at path.
//
// Returns (nil, false, nil) when the file does not exist.
// Returns (deps, true, nil) when the file is present and parseable.
// Returns (nil, false, err) on I/O or XML decode errors.
func parsePackagesConfig(path string) ([]ResolvedDep, bool, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}
		return nil, false, fmt.Errorf("open packages.config: %w", err)
	}
	defer func() { _ = f.Close() }()

	var cfg packagesConfigFile
	if err := xml.NewDecoder(f).Decode(&cfg); err != nil {
		return nil, false, fmt.Errorf("decode packages.config: %w", err)
	}

	var deps []ResolvedDep
	for _, pkg := range cfg.Packages {
		if pkg.ID == "" || pkg.Version == "" {
			continue // skip incomplete entries
		}
		depType := "runtime"
		if strings.EqualFold(pkg.DevelopmentDependency, "true") {
			depType = "dev"
		}
		deps = append(deps, ResolvedDep{
			Name:    pkg.ID,
			Version: pkg.Version,
			DepType: depType,
		})
	}

	return deps, true, nil
}

// ── .csproj fallback ─────────────────────────────────────────────────────────

// csprojFile is a minimal XML model for SDK-style .csproj files.
// Only <PackageReference> elements are extracted; all other elements are ignored.
type csprojFile struct {
	XMLName    xml.Name        `xml:"Project"`
	ItemGroups []csprojItemGroup `xml:"ItemGroup"`
}

type csprojItemGroup struct {
	PackageRefs []csprojPackageRef `xml:"PackageReference"`
}

type csprojPackageRef struct {
	// Include is the package name; e.g., Include="Newtonsoft.Json".
	Include string `xml:"Include,attr"`
	// Version may be an attribute or an inner element (both are supported in SDK-style).
	VersionAttr string `xml:"Version,attr"`
	// PrivateAssets="All" marks the package as dev/test-only.
	// Common for analyzers, code generators, and test SDKs.
	PrivateAssets string `xml:"PrivateAssets,attr"`
}

// parseCsprojDir scans root for *.csproj files and collects their declared
// PackageReference deps. Returns (deps, false, nil) — complete=false because
// the transitive closure cannot be determined without running dotnet restore
// (ACE risk on untrusted repos).
//
// Returns (nil, false, nil) when no *.csproj files are present.
func parseCsprojDir(root string) ([]ResolvedDep, bool, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, false, nil // unreadable dir: treat as absent
	}

	seen := make(map[string]bool) // lower(name)+"@"+version → already included
	var deps []ResolvedDep
	foundCsproj := false

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(strings.ToLower(e.Name()), ".csproj") {
			continue
		}
		foundCsproj = true
		pkgs, parseErr := parseSingleCsproj(filepath.Join(root, e.Name()))
		if parseErr != nil {
			// Malformed .csproj: skip this file; if others parse cleanly, continue.
			continue
		}
		for _, d := range pkgs {
			key := strings.ToLower(d.Name) + "@" + d.Version
			if !seen[key] {
				seen[key] = true
				deps = append(deps, d)
			}
		}
	}

	if !foundCsproj {
		return nil, false, nil
	}
	// complete=false: only declared (direct) deps are known; the full transitive
	// closure requires running dotnet restore (ACE risk). The caller MUST mark the
	// scan incomplete so the operator knows the coverage gap.
	return deps, false, nil
}

// parseSingleCsproj parses one .csproj file and returns its <PackageReference> entries.
func parseSingleCsproj(path string) ([]ResolvedDep, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var proj csprojFile
	if err := xml.NewDecoder(f).Decode(&proj); err != nil {
		return nil, fmt.Errorf("decode %s: %w", filepath.Base(path), err)
	}

	var deps []ResolvedDep
	for _, ig := range proj.ItemGroups {
		for _, ref := range ig.PackageRefs {
			if ref.Include == "" {
				continue
			}
			version := ref.VersionAttr
			if version == "" {
				// Version attribute missing; could be set via Directory.Packages.props
				// (central package management). Without it we cannot query OSV.
				// Skip this reference: including it without a version is worse than
				// omitting it (we cannot form a valid advisory query).
				continue
			}

			// <PrivateAssets>All</PrivateAssets> is the ONLY authoritative marker
			// for dev/test-only packages (Roslyn analyzers, test SDKs, etc.).
			// Without it, default to "runtime" (conservative: unknown ≠ safe).
			// Name-prefix heuristics are intentionally absent: a runtime package
			// whose name looks like a test SDK must not be suppressed.
			depType := "runtime"
			if strings.EqualFold(ref.PrivateAssets, "all") {
				depType = "dev"
			}
			deps = append(deps, ResolvedDep{
				Name:    ref.Include,
				Version: version,
				DepType: depType,
			})
		}
	}
	return deps, nil
}
