package cli

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ── detection tests ───────────────────────────────────────────────────────────

// TestPubDetect_LockfilePresent verifies that a directory containing pubspec.lock
// puts dart in scope via the registry-driven detection path.
func TestPubDetect_LockfilePresent(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte("packages: {}\n"), 0o644))

	eco := detectEcosystems(dir)
	assert.True(t, eco.active("dart"), "pubspec.lock present → Dart ecosystem detected")
	assert.False(t, eco.active("php"), "no composer.lock → PHP not detected")
	assert.False(t, eco.active("ruby"), "no Gemfile → Ruby not detected")
}

// TestPubDetect_ManifestOnlyPresent verifies that a directory with only pubspec.yaml
// (no pubspec.lock) still puts dart in scope, triggering detection that will
// result in an incomplete scan (unknown ≠ safe).
func TestPubDetect_ManifestOnlyPresent(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.yaml"), []byte("name: my_app\n"), 0o644))

	eco := detectEcosystems(dir)
	assert.True(t, eco.active("dart"), "pubspec.yaml present → Dart ecosystem detected (incomplete scan)")
}

// TestPubDetect_NeitherPresent verifies that a directory without any Dart files
// does not put dart in scope.
func TestPubDetect_NeitherPresent(t *testing.T) {
	dir := t.TempDir()

	eco := detectEcosystems(dir)
	assert.False(t, eco.active("dart"), "no pubspec.* files → Dart ecosystem not detected")
}

// ── parsePubspecLock tests ────────────────────────────────────────────────────

// TestParsePubspecLock_NoLockfile verifies that a missing pubspec.lock returns
// (nil, false, nil) — the caller must mark the scan incomplete.
func TestParsePubspecLock_NoLockfile(t *testing.T) {
	dir := t.TempDir()

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err, "missing lockfile must not be an error")
	assert.False(t, complete, "missing lockfile → complete=false")
	assert.Nil(t, deps, "missing lockfile → nil deps (no partial result)")
}

// TestParsePubspecLock_EmptyPackages verifies that a pubspec.lock with an empty
// packages map returns an empty complete closure (not an error).
func TestParsePubspecLock_EmptyPackages(t *testing.T) {
	dir := t.TempDir()
	lockContent := `# Generated by pub
packages:
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete, "empty packages → complete=true (project has zero deps)")
	assert.Empty(t, deps, "empty packages → empty closure")
}

// TestParsePubspecLock_HostedDepsOnly verifies full parsing of a typical pubspec.lock
// with only hosted dependencies. Dep-type is mapped correctly per the
// "direct main" / "direct dev" / "transitive" field.
func TestParsePubspecLock_HostedDepsOnly(t *testing.T) {
	dir := t.TempDir()
	lockContent := `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30b"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.11.0"
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "759701ea3fd9d27a0e5e6f9a6aa88e879a0e"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: "3d6e7963f3d7c44e3e5c7c3b2"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.24.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete, "valid pubspec.lock → complete=true")
	require.Len(t, deps, 3, "three hosted packages expected")

	byName := make(map[string]ResolvedDep)
	for _, d := range deps {
		byName[d.Name] = d
	}

	// "transitive" dependency → runtime
	asyncDep, ok := byName["async"]
	require.True(t, ok, "async package must be in closure")
	assert.Equal(t, "2.11.0", asyncDep.Version)
	assert.Equal(t, "runtime", asyncDep.DepType, "transitive dep must map to runtime")

	// "direct main" dependency → runtime
	httpDep, ok := byName["http"]
	require.True(t, ok, "http package must be in closure")
	assert.Equal(t, "1.1.0", httpDep.Version)
	assert.Equal(t, "runtime", httpDep.DepType, "direct main dep must map to runtime")

	// "direct dev" dependency → dev
	testDep, ok := byName["test"]
	require.True(t, ok, "test package must be in closure")
	assert.Equal(t, "1.24.0", testDep.Version)
	assert.Equal(t, "dev", testDep.DepType, "direct dev dep must map to dev")
}

// TestParsePubspecLock_NonHostedSkipped verifies that git, path, and sdk packages
// are excluded from the closure. These have no pub.dev registry identity and
// cannot match OSV Pub advisories; excluding them is safe (not false-clean).
func TestParsePubspecLock_NonHostedSkipped(t *testing.T) {
	dir := t.TempDir()
	lockContent := `packages:
  hosted_pkg:
    dependency: "direct main"
    description:
      name: hosted_pkg
      sha256: "abc123"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  git_pkg:
    dependency: "direct main"
    description:
      ref: main
      resolved-ref: "deadbeef"
      url: "https://github.com/owner/repo.git"
    source: git
    version: "0.0.0"
  path_pkg:
    dependency: "direct main"
    description:
      path: "../local_pkg"
      relative: true
    source: path
    version: "0.1.0"
  sdk_flutter:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete)
	require.Len(t, deps, 1, "only hosted packages must appear in the closure")
	assert.Equal(t, "hosted_pkg", deps[0].Name)
	assert.Equal(t, "1.0.0", deps[0].Version)
}

// TestParsePubspecLock_MalformedYAML verifies that a malformed pubspec.lock
// returns (nil, false, err) — complete=false prevents false-clean results.
func TestParsePubspecLock_MalformedYAML(t *testing.T) {
	dir := t.TempDir()
	badContent := `packages: {this is not valid yaml :`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(badContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	assert.Error(t, err, "malformed YAML must return an error")
	assert.False(t, complete, "malformed lockfile → complete=false")
	assert.Nil(t, deps, "malformed lockfile → nil deps (no partial result)")
}

// TestParsePubspecLock_UnknownDepTypeIsRuntime verifies that an unrecognised
// dependency type value defaults to "" (treated as runtime by mergeDepType),
// not to "dev" (which would suppress the advisory check).
func TestParsePubspecLock_UnknownDepTypeIsRuntime(t *testing.T) {
	dir := t.TempDir()
	lockContent := `packages:
  mystery_pkg:
    dependency: "unknown-type"
    description:
      name: mystery_pkg
      sha256: "abc"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete)
	require.Len(t, deps, 1)
	assert.Equal(t, "", deps[0].DepType,
		"unrecognised dep type must be empty string (conservative; mergeDepType treats it as runtime)")
}

// TestParsePubspecLock_MissingVersionSkipped verifies that a package entry
// with an empty version is silently skipped (degenerate entry) without
// failing the overall parse. The remainder of the closure is still returned
// with complete=true.
func TestParsePubspecLock_MissingVersionSkipped(t *testing.T) {
	dir := t.TempDir()
	// A package with an empty version field should be skipped.
	lockContent := `packages:
  good_pkg:
    dependency: "direct main"
    description:
      name: good_pkg
      sha256: "abc"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  no_version_pkg:
    dependency: "direct main"
    description:
      name: no_version_pkg
      sha256: "def"
      url: "https://pub.dartlang.org"
    source: hosted
    version: ""
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete)
	require.Len(t, deps, 1, "package with empty version must be skipped")
	assert.Equal(t, "good_pkg", deps[0].Name)
}

// TestParsePubspecLock_NullPackages verifies that a pubspec.lock file with
// a null/absent packages key returns an empty complete closure (valid for a
// project with zero dependencies).
func TestParsePubspecLock_NullPackages(t *testing.T) {
	dir := t.TempDir()
	lockContent := `# Generated by pub
sdks:
  dart: ">=3.0.0 <4.0.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete, "lockfile with no packages key → complete=true (zero deps)")
	assert.Nil(t, deps, "lockfile with no packages key → nil (empty closure)")
}

// TestParsePubspecLock_FlutterProject verifies parsing of a realistic Flutter
// project lockfile that mixes sdk, hosted, and transitive deps.
func TestParsePubspecLock_FlutterProject(t *testing.T) {
	dir := t.TempDir()
	// Typical Flutter pubspec.lock: flutter itself is an sdk dep (skipped),
	// plus several hosted transitive deps.
	lockContent := `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad35851ffe371d1741eba"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "ee67778f30230e04a1a5d1a9"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.18.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: "9e8c3a40"
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "pubspec.lock"), []byte(lockContent), 0o644))

	deps, complete, err := parsePubspecLock(dir)
	require.NoError(t, err)
	assert.True(t, complete)
	// sdk dep (flutter) must be excluded; 3 hosted deps remain
	require.Len(t, deps, 3, "flutter sdk dep excluded; 3 hosted deps remain")

	byName := make(map[string]ResolvedDep)
	for _, d := range deps {
		byName[d.Name] = d
	}

	assert.Equal(t, "1.3.0", byName["characters"].Version)
	assert.Equal(t, "runtime", byName["characters"].DepType)

	assert.Equal(t, "1.18.0", byName["collection"].Version)
	assert.Equal(t, "runtime", byName["collection"].DepType)

	assert.Equal(t, "3.0.0", byName["flutter_lints"].Version)
	assert.Equal(t, "dev", byName["flutter_lints"].DepType, "flutter_lints is a direct dev dep")

	_, flutterPresent := byName["flutter"]
	assert.False(t, flutterPresent, "flutter sdk dep must not appear in closure")
}

// ── pubDepType unit tests ─────────────────────────────────────────────────────

// TestPubDepType covers all known dependency field values from pubspec.lock
// and verifies the tri-state contract: only "direct dev" maps to "dev";
// everything else is runtime-or-unknown (never silently dev).
func TestPubDepType(t *testing.T) {
	t.Parallel()

	cases := []struct {
		input string
		want  string
	}{
		{"direct main", "runtime"},
		{"direct dev", "dev"},
		{"transitive", "runtime"},
		// Unrecognised values must default to "" (conservative; treated as runtime
		// by mergeDepType — unknown ≠ dev).
		{"", ""},
		{"unknown", ""},
		{"Direct Main", ""},  // case-sensitive match only
		{"direct test", ""},  // not a known pub dep type
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.input, func(t *testing.T) {
			t.Parallel()
			got := pubDepType(tc.input)
			assert.Equal(t, tc.want, got, "pubDepType(%q)", tc.input)
		})
	}
}

// ── adapter registration tests ────────────────────────────────────────────────

// TestPubAdapterRegistered verifies that the Pub lockfile-static adapter is present in
// the global registry after package init().
func TestPubAdapterRegistered(t *testing.T) {
	var pubAdapter *EcosystemAdapter
	for _, a := range EcosystemAdapters() {
		a := a
		if a.Language == "dart" {
			pubAdapter = &a
			break
		}
	}
	require.NotNil(t, pubAdapter, "dart adapter must be registered after package init()")
	assert.Equal(t, "Pub", pubAdapter.Ecosystem, "dart adapter must use Pub ecosystem")
	assert.Contains(t, pubAdapter.DetectFiles, "pubspec.lock",
		"pubspec.lock must be a detect file for zero-config auto-detection")
	assert.Contains(t, pubAdapter.DetectFiles, "pubspec.yaml",
		"pubspec.yaml must be a detect file so manifest-only projects trigger incomplete")
	assert.NotNil(t, pubAdapter.ParseLockfile, "ParseLockfile must be set")
	assert.Nil(t, pubAdapter.NormalizeName,
		"NormalizeName must be nil (Pub names are case-sensitive and match OSV as-is)")
}

// TestPubResolveLanguageDart verifies that --language dart narrows the scan
// to the Dart ecosystem via resolveLanguage.
func TestPubResolveLanguageDart(t *testing.T) {
	eco, err := resolveLanguage("dart", ecosystems{})
	require.NoError(t, err)
	assert.True(t, eco.active("dart"), "--language dart must put dart in scope")
	assert.False(t, eco.active("go"), "--language dart must not put go in scope")
	assert.False(t, eco.active("php"), "--language dart must not put php in scope")
}

// ── scan guard tests ──────────────────────────────────────────────────────────

// buildPubTestBinary compiles the commit0-analyzer CLI binary into a temp dir and
// returns its path. Shared by the guard tests below.
func buildPubTestBinary(t *testing.T) string {
	t.Helper()
	cliBin := filepath.Join(t.TempDir(), "commit0-analyzer")
	out, err := exec.Command("go", "build", "-o", cliBin, "github.com/commit0-dev/commit0-analyzer/cmd/commit0-analyzer").CombinedOutput()
	require.NoError(t, err, "build commit0-analyzer CLI:\n%s", out)
	return cliBin
}

// TestPubScanGuard_DartOnlyAutoDetectPassesGuard is an end-to-end guard test.
//
// It verifies that a Dart-only repository (containing only pubspec.lock, with no
// go.mod / package.json / Cargo.toml / etc.) does NOT hit the early-exit
// "no recognised ecosystem manifest" guard in runScan.
//
// Before the fix to scan.go:306, eco.active("dart") was omitted from the guard condition:
//
//	if !eco.active("go") && !eco.active("js") && ... && !eco.active("elixir") { // missing !eco.active("dart")
//
// This caused every Dart-only repo to exit with ExitOperationalError(3) and the
// message "contains no recognised ecosystem manifest", killing the lockfile-static adapter
// loop before it ever ran. The guard must include !eco.active("dart") so that a repo with
// pubspec.lock (eco.active("dart")=true) is not rejected.
func TestPubScanGuard_DartOnlyAutoDetectPassesGuard(t *testing.T) {
	cliBin := buildPubTestBinary(t)

	// Dart-only dir: only pubspec.lock, no other ecosystem manifests.
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "pubspec.lock"),
		[]byte("packages: {}\nsdks:\n  dart: \">=3.0.0 <4.0.0\"\n"),
		0o644,
	))

	var stderrBuf bytes.Buffer
	cmd := exec.Command(cliBin, "scan", dir, "--source", "osv", "--offline")
	cmd.Stderr = &stderrBuf
	_ = cmd.Run()

	stderr := stderrBuf.String()
	t.Logf("stderr: %q", stderr)

	// The guard must NOT fire. If it fires, scan.go:306 still omits !eco.active("dart").
	assert.NotContains(t, stderr, "no recognised ecosystem manifest",
		"Dart-only repo (pubspec.lock detected → dart in scope) must NOT hit the "+
			"no-ecosystem guard; a detected dart ecosystem must count as something to scan")
}

// TestPubScanGuard_LanguageDartFlagPassesGuard verifies that --language dart on a
// directory that contains pubspec.lock does NOT trigger the early-exit guard.
//
// resolveLanguage("dart") returns ecosystems{"dart":true}. Without !eco.active("dart") in
// the guard, this path also exits with ExitOperationalError(3) before any scan runs,
// breaking the --language dart narrowing filter entirely.
func TestPubScanGuard_LanguageDartFlagPassesGuard(t *testing.T) {
	cliBin := buildPubTestBinary(t)

	dir := t.TempDir()
	require.NoError(t, os.WriteFile(
		filepath.Join(dir, "pubspec.lock"),
		[]byte("packages: {}\n"),
		0o644,
	))

	var stderrBuf bytes.Buffer
	cmd := exec.Command(cliBin, "scan", dir, "--language", "dart", "--source", "osv", "--offline")
	cmd.Stderr = &stderrBuf
	_ = cmd.Run()

	stderr := stderrBuf.String()
	t.Logf("stderr: %q", stderr)

	assert.NotContains(t, stderr, "no recognised ecosystem manifest",
		"--language dart on a dir with pubspec.lock must NOT hit the no-ecosystem guard")
}
